name: setNamePlugin
main: nameSet\nameSet
version: 0.1
api:
    - 1.13.1
    - 1.0.0
author: Redstonealmeida

commands:
    setplayernick:
        description: setplayernick
        aliases: [fake,nick,admnick]
        use: "/setplayernick"
        permission: setplayernick.command

permission:
    setplayernick.command:
    description: "setplayernick"
    default: op
